version: "3,7"
services:
    micro_01:
        build:
            args:
                user: eduardo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes: ./:/var/www
